### ISSUE TITLE
BUG while using user_followers() code expample: followers = await cl.user_followers(cl.user_id)

### ISSUE THREAD

**Issue by gavinchris37** [subzeroid/aiograpi#59]
### Try HikerAPI SaaS with a free trial https://hikerapi.com/p/KhMxYMSn

**Describe the bug**
followers = await cl.user_followers(cl.user_id)
when using the above function im getting the below error message in the output 

**To Reproduce**
followers = await cl.user_followers(cl.user_id)

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

**Expected behavior**

**Screenshots**

**Output**
Status 201: JSONDecodeError in public_request (url=https://www.instagram.com/username/?__a=1&__d=dis) >>> 
'NoneType' object has no attribute 'cookies'
Traceback (most recent call last):
  File "D:\Projects\Python\raph\venv\Lib\site-packages\aiograpi\mixins\user.py", line 891, in user_followers
    users = await self.user_followers_gql(user_id, amount)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\raph\venv\Lib\site-packages\aiograpi\mixins\user.py", line 780, in user_followers_gql
    items, end_cursor = await self.user_followers_gql_chunk(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\Python\raph\venv\Lib\site-packages\aiograpi\mixins\user.py", line 732, in user_followers_gql_chunk
    self.inject_sessionid_to_public()
  File "D:\Projects\Python\raph\venv\Lib\site-packages\aiograpi\mixins\auth.py", line 851, in inject_sessionid_to_public
    self.graphql.set_cookies(cookie)
  File "D:\Projects\Python\raph\venv\Lib\site-packages\aiograpi\reqwests.py", line 87, in set_cookies
    self._client.cookies.set(k, v)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cookies'

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]
 - aiograpi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by Paintitai** [comment]
the same bug, any idea?

**Comment by Paintitai** [comment]
@proxies.setter
    def proxies(self, p):
        self._proxies = p
        self._set_client()
 
looks like setter never call

**Comment by luca-arch** [comment]
I have found a workaround, see https://github.com/subzeroid/aiograpi/issues/90

**Comment by subzeroid** [comment]
Duplicate of #90 / #177, all the same root cause (`graphql.session._client = None` because `_set_client()` was only triggered from the proxy setter, which wasn't always invoked). Fixed in current main — `pip install -U aiograpi` (latest 0.7.2). `Client.__init__` now always calls `set_proxy(None)` which goes through the setter on all three sessions.
