### ISSUE TITLE
[BUG] validation error for Location

### ISSUE THREAD

**Issue by ajkessel** [subzeroid/aiograpi#72]
This is with the latest git build
```
[ERROR@aiograpi] 1 validation error for Location
external_id
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing
Traceback (most recent call last):
  File "/path/lib/python3.10/site-packages/aiograpi/mixins/media.py", line 256, in media_info
    media = await self.media_info_gql(media_pk)
  File "/path/lib/python3.10/site-packages/aiograpi/mixins/media.py", line 210, in media_info_gql
    extract_location(data["shortcode_media"]["location"])
  File "/path/lib/python3.10/site-packages/aiograpi/extractors.py", line 305, in extract_location
    return Location(**data)
  File "/path/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Location
external_id
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='None', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing
```

**Comment by ajkessel** [comment]
Seems like the issue here is external_id is expected to be an `int`, so this is one to fix it:
```
--- aiograpi/extractors.py  2024-07-08 10:43:51.016256124 -0700
+++ fixed/extractors.py 2024-07-08 11:35:29.094408582 -0700
@@ -288,7 +288,7 @@
     if not data:
         return None
     data["pk"] = data.get("id", data.get("pk", data.get("location_id", None)))
-    data["external_id"] = int(str(data.get("external_id", data.get("facebook_places_id"))))
+    data["external_id"] = str(data.get("external_id", data.get("facebook_places_id")))
     data["external_id_source"] = data.get(
         "external_id_source", data.get("external_source")
     )
```

**Comment by subzeroid** [comment]
Fixed in 7a9cf1f (auto-closed by the commit message).

`Location.external_id` is typed `Optional[int]`, but `extract_location` was passing the raw IG value through without coercion. When IG returned the field missing, `None`, `""`, or the literal string `"None"`, pydantic raised `int_parsing` and bubbled out of `media_info_gql`.

Your proposed patch (`int(...)`) was the right direction; the version that landed handles the missing-value cases too:

```python
ext = data.get("external_id") or data.get("facebook_places_id")
data["external_id"] = int(ext) if ext not in (None, "", "None") else None
```

Will ship in the next PyPI bump. Thanks for the precise repro and patch — sat in the queue too long, my bad.
