### ISSUE TITLE
[BUG] `user_followers_gql_chunk()` raises `AttributeError`

### ISSUE THREAD

**Issue by luca-arch** [subzeroid/aiograpi#90]
### Try HikerAPI SaaS with a free trial https://hikerapi.com/p/KhMxYMSn

**Describe the bug**
> AttributeError: 'NoneType' object has no attribute 'cookies'

**To Reproduce**
1. Log in via session as per [Use Sessions](https://subzeroid.github.io/aiograpi/usage-guide/best-practices.html)
2. Await `user_followers_gql_chunk()`
3. See the exception

**Traceback**
```
INFO:aiograpi:https://i.instagram.com/api/v1/feed/timeline/
INFO:httpx:HTTP Request: POST https://i.instagram.com/api/v1/feed/timeline/ "HTTP/1.1 200 OK"
INFO:graphql_request:*****@mail.com [200] POST https://i.instagram.com/api/v1/feed/timeline/ (269.0.0.18.75, OnePlus 6T Dev)
ERROR:root:'NoneType' object has no attribute 'cookies'
Traceback (most recent call last):
  File "/mnt/modules/instafollow/worker/copier.py", line 134, in process
    await copy_user_followers()
  File "/mnt/modules/instafollow/worker/copier.py", line 119, in copy_user_followers
    resp = await ig_client.user_followers_gql_chunk(user_id, end_cursor = None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiograpi/mixins/user.py", line 732, in user_followers_gql_chunk
    self.inject_sessionid_to_public()
  File "/usr/local/lib/python3.12/site-packages/aiograpi/mixins/auth.py", line 851, in inject_sessionid_to_public
    self.graphql.set_cookies(cookie)
  File "/usr/local/lib/python3.12/site-packages/aiograpi/reqwests.py", line 87, in set_cookies
    self._client.cookies.set(k, v)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cookies'
```

**Desktop (please complete the following information):**
 - OS: python:3.12.5-bookworm (arm Docker image)
 - Python version 3.12.5
 - aiograpi 0.0.3
 - moveipy n/a
 - imagemagick n/a

**Additional context**
I think this relates to https://github.com/subzeroid/aiograpi/issues/59, as the `self._set_client()` setter is never invoked

**Comment by subzeroid** [comment]
Fixed in current main, same fix as #177. `pip install -U aiograpi` (latest 0.7.2).

The root cause was that `graphql` session's `_client` started as `None` and `_set_client()` was only called from the proxy setter. Now `Client.__init__` always calls `set_proxy(None)` which goes through the setter on all three sessions (public, private, graphql), so `_client` is guaranteed non-None before any `inject_sessionid_to_public()` runs.

Your workaround (`ig_client.graphql._set_client()`) is no longer needed.

Side note: I'd also recommend `pip install -U aiograpi` for several other reasons — your trace shows the old hardcoded device `269.0.0.18.75 / OnePlus 6T Dev`. We've since moved to the upstream `config.APP_SETTINGS` rotation, which uses modern app versions (364.0.0.35.86 + 385.0.0.47.74) and reduces challenge rates noticeably.
